/** All phone copy. Wording rules: docs/decisions/0002-wording.md (pnpm lint:words). No "wrong", no "failed", a missed day says "Welcome back". */
export const strings = {
  join: { title: 'Enter the code on your TV', box: (i: number) => `Code character ${i + 1} of 6`, join: 'Join', scan: "Scan the TV's code",
    scanTitle: 'Point at the code on the TV', scanLabel: "Camera, looking for the TV's QR code", typeInstead: 'Type it instead', review: 'Review words',
    joining: 'Joining your TV…', server: (u: string) => `Lingo server: ${u}`, serverChange: 'Change', serverLabel: 'Lingo server address', serverSave: 'Save',
    serverInvalid: 'That address does not look right. Example: 192.168.1.20:4000' },
  hint: { badCode: 'Check the six characters on the TV.', unknownCode: 'No TV with that code. Check the code on the TV.',
    unreachable: "Can't reach Lingo. Check that the phone is on the same Wi-Fi.", cameraOff: 'Camera is off. Type the code instead.',
    invalidChar: 'Codes use letters and the digits 2–9, never 0, O, 1 or I.' },
  live: { status: { none: 'Not connected', joining: 'Connecting to your TV…', joined: 'Connected to your TV', reconnecting: 'Reconnecting…' },
    noClip: 'Watching on your TV', empty: 'Words you save on the TV appear here.', chipLabel: (w: string) => `${w}. Show the meaning and hear it`,
    hear: 'Hear it', hearLabel: (w: string) => `Hear ${w}`, quizNow: 'Quiz me now', quizReady: 'The clip is over. Quiz me now is ready.', forget: 'Use another TV' },
  quiz: { counts: (due: number, fresh: number) => `${due} due · ${fresh} new`, position: (i: number, n: number) => `${i} of ${n}`,
    reveal: 'Tap to see the meaning', frontLabel: (w: string) => `${w}. Tap to see the meaning`, backLabel: (w: string, g: string) => `${w}: ${g}`,
    grades: { again: 'Again', hard: 'Hard', good: 'Good', easy: 'Easy' },
    gradeLabel: (g: 'again' | 'hard' | 'good' | 'easy', w: string) => `${strings.quiz.grades[g]}: schedule ${w}`,
    retry: "That didn't reach Lingo. Try again.", loadError: "Can't load your words right now.", tryAgain: 'Try again',
    doneTitle: 'Done for today', doneBody: (n: number) => (n === 1 ? '1 word reviewed. See you tomorrow.' : `${n} words reviewed. See you tomorrow.`),
    sentToTv: 'Sent to your TV', seeProgress: 'See progress', emptyTitle: 'Nothing to review right now.', emptyBody: 'Words you save on the TV land here.' },
  progress: { day: (n: number) => `Day ${n}`, welcomeBack: 'Welcome back', first: 'Your first review starts day 1.',
    bandsTitle: 'Words known by level (approximate)', bandValue: (k: number, s: number) => `${k} of ${s}`,
    bandLabel: (l: string, k: number, s: number) => `Level ${l}, approximate: ${k} of ${s} saved words known`,
    clips: (n: number) => (n === 1 ? '1 clip watched' : `${n} clips watched`),
    dueNow: (n: number) => (n === 1 ? '1 word to review now' : `${n} words to review now`),
    dueTomorrow: (n: number) => (n === 1 ? '1 word to review tomorrow' : `${n} words to review tomorrow`),
    nothingDue: 'Nothing to review yet.', reviewNow: 'Review now', loadError: "Can't load your progress right now." },
  tabs: { live: 'Live', review: 'Review', progress: 'Progress' },
} as const
