export const strings = {
  rail: { watch: 'Watch', review: 'Review', words: 'Words', plus: 'Plus', settings: 'Settings',
    label: (name: string) => `${name}. Menu`, reviewLabel: 'Review: words due today', wordsLabel: 'Words: everything you saved', plusLabel: 'Lingo Plus', settingsLabel: 'Settings', watchLabel: 'Watch: home' },
  common: { back: 'Back', retry: 'Try again', error: 'Something didn\u2019t work on our side.', saveError: 'Couldn\u2019t save. Try again.', loading: 'Loading' },
  level: { about: (l: string) => `about ${l}`, label: (l: string) => `Level about ${l}` },
  time: { minutes: (m: number) => `${m} min` },
  home: { continue: 'Continue', justRight: (l: string) => `Just right for you · about ${l}`, harder: (l: string) => `A bit harder · about ${l}`, fresh: 'New this week', watch: 'Watch',
    resume: (at: string) => `Resume from ${at}`, meet: 'Words you\u2019ll meet', watchLabel: (t: string) => `Watch ${t}`, resumeLabel: (t: string, at: string) => `Resume ${t} from ${at}`,
    meetLabel: (t: string) => `Words you\u2019ll meet in ${t}`, cardLabel: (t: string, l: string, min: string) => `Open ${t}. About ${l}, ${min}.`,
    loading: 'Loading clips', empty: 'No clips in this language yet.', emptyAction: 'Open Settings' },
  clip: { wordsYoullMeet: "Words you'll meet", watch: 'Watch', challenge: 'Watch in Challenge mode', preparing: (m: number) => `Preparing subtitles — about ${m} minutes.`,
    challengePlus: 'Challenge mode · Plus', challengeLabel: 'Watch in Challenge mode: native line hidden, Menu shows it',
    challengePlusLabel: 'Challenge mode is part of Lingo Plus. Select to see Lingo Plus', addContinue: 'Add to Continue', inContinue: 'In Continue', added: 'Added to Continue.',
    preparingBody: 'This page checks again by itself.', notFound: 'This clip isn\u2019t available.', noWords: 'No new words at your level in this clip.',
    meetLabel: (ws: string) => `Words you\u2019ll meet: ${ws}` },
  explain: { save: 'Save word', replay: 'Replay', slower: 'Slower', continue: 'Continue', saved: (n: number) => `Saved. ${n} ${n === 1 ? 'word' : 'words'} this clip.`, limit: "That's 20 today. Lingo Plus removes the limit.", plusCta: 'See Lingo Plus',
    continueHint: 'Back to continue watching', slowerPlus: 'Slower · Plus', normalSpeed: 'Normal speed',
    slowerUpsell: 'Slower playback is part of Lingo Plus.', savedState: 'Saved', saveError: 'Couldn\u2019t save. Try again.',
    saveLabel: (w: string) => `Save word: ${w}`, savedLabel: (w: string) => `Saved: ${w}`, wordLabel: (w: string) => `Explain ${w}`, wordSavedLabel: (w: string) => `Explain ${w}, saved`,
    rankChip: (rank: number, level: string) => `rank ${rank} · about ${level}` },
  player: { stage: 'Video. Press Select to pause and explain this line.', stagePaused: 'Video, paused. Press Select to continue watching.', pausedHint: 'Paused · Select to continue', hold: 'Pausing at the end of the line', challenge: 'Challenge', slow: '0.75×' },
  sheet: { title: 'Playback', speed: 'Speed', hint: 'Select or left and right to change · Back to close', rateNormal: '1×', rateSlow: '0.75×', sizeValue: (pct: number) => `${pct} %`, rowLabel: (name: string, value: string) => `${name}: ${value}. Select or left and right to change` },
  summary: { newWords: (n: number, lang: 'de' | 'en') => (lang === 'de' ? (n === 1 ? '1 neues Wort' : `${n} neue Wörter`) : n === 1 ? '1 new word' : `${n} new words`),
    phoneSent: (name: string) => `Quiz sent to ${name}.`, phoneResult: (c: number, n: number) => `Phone quiz: ${c} of ${n} right.`, lastQuiz: (c: number, n: number) => `Last quiz on TV: ${c} of ${n} right.`, quizTv: 'Quiz on TV', quizPhone: 'Quiz on your phone', again: 'Watch again', next: 'Next clip', none: 'You watched the whole clip. Try Challenge mode next time?' },
  quiz: { progress: (i: number, n: number) => `${i} of ${n}`, replayLine: 'Replay the line', done: (c: number, n: number) => `${c} of ${n} right`,
    meaningKind: 'What does it mean?', clozeKind: 'Fill the gap', right: (o: string) => `Right: ${o}`, answerIs: (o: string) => `The answer: ${o}`,
    inClip: (native: string) => `In the clip: ${native}`, continue: 'Continue', optionLabel: (o: string, i: number, n: number) => `Answer ${i} of ${n}: ${o}`,
    empty: 'This clip has no quiz yet.', levelUp: (l: string) => `Your level is now about ${l}.`, next: 'Next clip', again: 'Watch again', finish: 'Done' },
  words: { empty: 'Words you save while watching land here.', filters: ['All', 'Due today', 'Learned'],
    title: 'Words', hint: 'Left and right change the list. Select plays the line.', emptyDue: 'Nothing is due today.',
    emptyLearned: 'Words you know well show up here after a few reviews.', findClip: 'Find a clip to watch', dueToday: 'Due today', dueTomorrow: 'Due tomorrow',
    dueIn: (n: number) => `Due in ${n} days`, rowLabel: (lemma: string, gloss: string, due: string, clip: string, playable: boolean) => `${lemma}: ${gloss}. ${due}. From ${clip}.${playable ? ' Select to play the line.' : ''}`,
    filterLabel: (name: string, count: number) => `${name}: ${count} words`, noLine: 'This line isn\u2019t available yet.' },
  pair: { title: 'Pair your phone for quizzes?', body: 'Scan the code or type it in the Lingo app.', later: 'Later', connected: (name: string) => `${name} connected`, qrLabel: (code: string) => `QR code to pair your phone, code ${code.split('').join(' ')}`, waiting: 'Getting a code…', defaultPhone: 'Your phone', continue: 'Continue' },
  firstRun: { learning: "I'm learning", speak: 'I speak', placement: 'Did you understand this line?', yes: 'Yes', mostly: 'Mostly', no: 'No',
    placementTitle: 'A quick check of your level', placementBody: 'Six short lines. Answer honestly; you can change your level in Settings.',
    item: (i: number, n: number) => `${i} of ${n}`, skip: 'Skip · start at about A2', learningLabel: (name: string) => `Learn ${name}`, speakLabel: (name: string) => `I speak ${name}`,
    yesLabel: 'Yes, I understood it', mostlyLabel: 'I mostly understood it', noLabel: 'No, not yet', skipLabel: 'Skip the check and start at about A2', done: 'Start watching' },
  settings: { learning: 'Learning language', native: 'I speak', level: 'Level', nativeLine: 'Native line', nativeLineOpts: { always: 'Always', onPause: 'On pause', never: 'Never' }, autoPause: 'Pause at the end of each line', cueSize: 'Subtitle size', pair: 'Pair phone', plus: 'Lingo Plus', about: 'About & attributions',
    title: 'Settings', learningOpts: { de: 'Deutsch', en: 'English' }, autoPauseOpts: { on: 'On', off: 'Off' }, sizeValue: (pct: number) => `${pct} %`,
    pairValue: (name: string | null) => (name ? `Connected: ${name}` : 'Not paired'), plusValue: (on: boolean) => (on ? 'On' : 'Off'), open: 'Open',
    rowLabel: (name: string, value: string) => `${name}: ${value}. Left and right to change`, linkLabel: (name: string, value: string) => `${name}: ${value}. Select to open`,
    hint: 'Left and right change a value. Back to go home.' },
  about: { title: 'About & attributions', machine: 'Subtitles are transcribed and translated by machine. Explanations and quizzes are written by AI and spot-checked by people.',
    fonts: 'Noto Sans and Manrope: SIL Open Font License 1.1.',
    freq: 'Word frequencies: hermitdave/FrequencyWords (OpenSubtitles 2018), CC BY-SA 4.0.', clips: 'Clips' },
  plus: {
    title: 'Lingo Plus',
    body: (rate: boolean) => (rate ? 'Lingo Plus adds Challenge mode, unlimited saved words and slower playback at 0.75×.' : 'Lingo Plus adds Challenge mode and unlimited saved words.'),
    price: (p: string) => `${p} per month`,
    priceUnavailable: 'Price unavailable right now.',
    buy: 'Subscribe', restore: 'Restore purchase', back: 'Back',
    subscribeLabel: (p: string) => `Subscribe to Lingo Plus for ${p} per month`,
    restoreLabel: 'Restore an earlier Lingo Plus purchase', backLabel: 'Back to the previous screen',
    loading: 'Checking Lingo Plus…',
    busy: { purchasing: 'Opening the Amazon purchase…', verifying: 'Confirming with Amazon…', restoring: 'Looking for your purchase…' },
    retry: 'That didn’t go through. Nothing was charged that we can see. Try again or restore.',
    pending: 'Your purchase is safe with Amazon. We’ll finish setting up Lingo Plus the next time you open Lingo.',
    restoreEmpty: 'No Lingo Plus purchase found for this Amazon account.',
    restoreError: 'Couldn’t reach the Amazon store just now. Try Restore purchase again in a minute.',
    active: 'You have Lingo Plus.',
    renews: (d: string) => `Renews ${d}.`, cancels: (d: string) => `Ends ${d}.`,
    cancelHow: 'To cancel, open amazon.com/appstoresubscriptions.',
    demo: 'Lingo Plus is on for everyone in this demo.',
    unavailable: 'Lingo Plus isn’t available on this device yet.',
  },
  streak: { back: 'Welcome back', day: (n: number) => `Day ${n}` },
  offline: 'Can\u2019t reach Lingo. Check the network and press Select to retry.',
  playbackOff: { title: 'Video plays on Fire TV with Fire OS for now.', body: 'Vega support is experimental, and its video player isn\u2019t ready yet.', back: 'Back', backLabel: 'Back to the previous screen' },
}
