// Expo config plugin: build react-native-iap (OpenIAP) against the Amazon Appstore SDK and ship the Appstore public key.
// - gradle.properties: openiapStore=amazon. react-native-iap 16.7.x android/openiap-store.gradle reads it first ("explicit") and
//   then pulls io.github.hyochan.openiap:openiap-google-amazon. Any older openiapStore / fireOsEnabled line is replaced.
// - android/app/src/main/assets/AppstoreAuthenticationKey.pem, copied from apps/expo/amazon/ if present. Without it App Tester
//   answers AUTH_TOKEN_VERIFICATION_FAILURE. The key is never committed (apps/expo/.gitignore).
// android/ is generated by `EXPO_TV=1 npx expo prebuild --clean` and not committed, so the edits live here.
// https://developer.amazon.com/docs/appstore-sdk/integrate-appstore-sdk.html · https://developer.amazon.com/docs/appstore-sdk/appstore-sdk-troubleshooting.html
// Config plugins: https://docs.expo.dev/config-plugins/plugins/ · mods: https://docs.expo.dev/config-plugins/mods/
const fs = require('node:fs')
const path = require('node:path')
const { withDangerousMod, withGradleProperties } = require('expo/config-plugins')

const PEM = 'AppstoreAuthenticationKey.pem'
const REPLACED = new Set(['openiapStore', 'fireOsEnabled'])

/** Drops any openiapStore / fireOsEnabled property and appends openiapStore=amazon. Idempotent. */
function setStoreProperty(props) {
  const kept = props.filter((p) => !(p.type === 'property' && REPLACED.has(p.key)))
  return [...kept, { type: 'property', key: 'openiapStore', value: 'amazon' }]
}
/** Where the Appstore SDK looks for the key. */
function pemTarget(projectRoot) { return path.join(projectRoot, 'android', 'app', 'src', 'main', 'assets', PEM) }
/** Where the developer puts the key downloaded from Developer Console → App → Public Key. */
function pemSource(projectRoot) { return path.join(projectRoot, 'amazon', PEM) }

let warned = false
function withAmazonIap(config) {
  config = withGradleProperties(config, (cfg) => {
    cfg.modResults = setStoreProperty(cfg.modResults)
    return cfg
  })
  return withDangerousMod(config, ['android', async (cfg) => {
    const root = cfg.modRequest.projectRoot
    const from = pemSource(root)
    if (fs.existsSync(from)) {
      const to = pemTarget(root)
      fs.mkdirSync(path.dirname(to), { recursive: true })
      fs.copyFileSync(from, to)
    } else if (!warned) {
      warned = true
      console.warn(`[withAmazonIap] Fire OS IAP needs ${PEM} from the Developer Console → App → Public Key. Put it at ${path.relative(root, from)}.`)
    }
    return cfg
  }])
}

module.exports = withAmazonIap
module.exports.setStoreProperty = setStoreProperty
module.exports.pemTarget = pemTarget
module.exports.pemSource = pemSource
