// Expo config plugin: turn on react-native-tvos key-down events on Android.
// Without it ReactAndroidHWInputDeviceHelper sends only key-up (eventKeyAction 1) for plain keys; with it a press arrives as
// 0 then 1, which lets the Player time ◄ holds itself. Held D-pad/Select keys arrive as long<Key> 0 / long<Key> 1 either way.
// Flag: ReactFeatureFlags.enableKeyDownEvents (react-native-tvos packages/react-native/ReactAndroid/src/main/java/com/facebook/react/config/ReactFeatureFlags.kt)
// android/ is generated by `EXPO_TV=1 npx expo prebuild --clean` and not committed, so the edit lives here.
// Config plugins: https://docs.expo.dev/config-plugins/plugins/ · withMainApplication: https://docs.expo.dev/config-plugins/mods/
const { withMainApplication } = require('expo/config-plugins')

const IMPORT = 'import com.facebook.react.config.ReactFeatureFlags'
const FLAG = 'ReactFeatureFlags.enableKeyDownEvents = true'

function addKeyDownFlag(src, language) {
  if (src.includes(FLAG)) return src
  if (language !== 'kt') throw new Error(`withKeyDownEvents: expected MainApplication.kt, got ${language}`)
  let out = src.replace(/^(package [^\n]+\n)/m, `$1\n${IMPORT}\n`)
  const onCreate = /(override fun onCreate\(\)\s*\{\s*\n\s*super\.onCreate\(\)\s*\n)/
  if (!onCreate.test(out)) throw new Error('withKeyDownEvents: MainApplication.onCreate with super.onCreate() not found')
  out = out.replace(onCreate, `$1    ${FLAG}\n`)
  return out
}

module.exports = function withKeyDownEvents(config) {
  return withMainApplication(config, (cfg) => {
    cfg.modResults.contents = addKeyDownFlag(cfg.modResults.contents, cfg.modResults.language)
    return cfg
  })
}
module.exports.addKeyDownFlag = addKeyDownFlag
